### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by paulsykes** [chmorgan/libesphttpd_linux_example#1]
Following the build instructions I get the following error when running make

paul@ae25:~/work/libesphttpd_linux_example/build$ make
[  4%] Creating directories for 'esphttpd'
[  8%] No download step for 'esphttpd'
[ 12%] No patch step for 'esphttpd'
[ 16%] No update step for 'esphttpd'
[ 20%] Performing configure step for 'esphttpd'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/paul/work/libesphttpd_linux_example/build/esphttpd-prefix/src/esphttpd-build
[ 25%] Performing build step for 'esphttpd'
[  7%] Building C object CMakeFiles/esphttpd.dir/core/httpd-freertos.c.o
/home/paul/work/libesphttpd_linux_example/libesphttpd/core/httpd-freertos.c: In function ‘sslCreateContext’:
/home/paul/work/libesphttpd_linux_example/libesphttpd/core/httpd-freertos.c:152:23: error: implicit declaration of function ‘TLS_server_method’ [-Werror=implicit-function-declaration]
     ctx = SSL_CTX_new(TLS_server_method());
                       ^
/home/paul/work/libesphttpd_linux_example/libesphttpd/core/httpd-freertos.c:152:23: error: passing argument 1 of ‘SSL_CTX_new’ makes pointer from integer without a cast [-Werror=int-conversion]
In file included from /home/paul/work/libesphttpd_linux_example/libesphttpd/include/libesphttpd/httpd-freertos.h:14:0,
                 from /home/paul/work/libesphttpd_linux_example/libesphttpd/core/httpd-freertos.c:31:
/usr/include/openssl/ssl.h:2131:10: note: expected ‘const SSL_METHOD * {aka const struct ssl_method_st *}’ but argument is of type ‘int’
 SSL_CTX *SSL_CTX_new(const SSL_METHOD *meth);
          ^
/home/paul/work/libesphttpd_linux_example/libesphttpd/core/httpd-freertos.c: In function ‘platHttpServerTask’:
/home/paul/work/libesphttpd_linux_example/libesphttpd/core/httpd-freertos.c:489:51: error: implicit declaration of function ‘SSL_has_pending’ [-Werror=implicit-function-declaration]
                             bytesStillAvailable = SSL_has_pending(pRconn->ssl);
                                                   ^
cc1: all warnings being treated as errors
CMakeFiles/esphttpd.dir/build.make:158: recipe for target 'CMakeFiles/esphttpd.dir/core/httpd-freertos.c.o' failed
make[5]: *** [CMakeFiles/esphttpd.dir/core/httpd-freertos.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/esphttpd.dir/all' failed
make[4]: *** [CMakeFiles/esphttpd.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/esphttpd.dir/build.make:110: recipe for target 'esphttpd-prefix/src/esphttpd-stamp/esphttpd-build' failed
make[2]: *** [esphttpd-prefix/src/esphttpd-stamp/esphttpd-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/esphttpd.dir/all' failed
make[1]: *** [CMakeFiles/esphttpd.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chmorgan** [comment]
Hi @paulsykes.

What distribution are you using?

**Comment by paulsykes** [comment]
Hi @chmorgan , ubuntu 16.04 and cmake 3.9.1. cmake from cmake.org as the newest version in the ubuntu 16.04 repos is  3.5.1 and you have a minimum requirement of 3.9.

**Comment by paulsykes** [comment]
Hi @chmorgan, ah probably this. In a hurry so will check later, but don't want you to waste time on it. Looks like my ssl is old. Will confirm later after testing.

> SSLv23_method(void), SSLv23_server_method(void), SSLv23_client_method(void)
> Use of these functions is deprecated. They have been replaced with TLS_Method(), TLS_server_method() and TLS_client_method() respectively. New code should use those functions instead.

**Comment by chmorgan** [comment]
Ahh, that makes sense. I retested here with F27 and it built ok so it
seemed natural to look at differing versions of libraries. If you'd like to
add some build time conditionals to use the older methods that works too
btw, 16.04 isn't all that old!
