### ISSUE TITLE
/usr/bin/ld: -r and -pie may not be used together

### ISSUE THREAD

**Issue by lumax** [chmorgan/libesphttpd_linux_example#2]
Hello,
i would like to run this linux example on ubuntu 18.04.4 but got the following error:

make[6]: Entering directory '/opt/source/libesphttpd_linux/libesphttpd_linux_example/build/httpd-prefix/src/httpd-build'
[ 20%] Generating libwebpages-espfs.a
cd /opt/source/libesphttpd_linux/libesphttpd_linux_example/httpd/html && find | /opt/source/libesphttpd_linux/libesphttpd_linux_example/build/install/bin/mkespfsimage > /opt/source/libesphttpd_linux/libesphttpd_linux_example/build/httpd-prefix/src/httpd-build/webpages.espfs
wifi/wifi.tpl (55%, heatshrink)
wifi/connecting.html (48%, gzip)
wifi/140medley.min.js (61%, gzip)
wifi/icons.png (100%, none)
wifi/style.css (62%, gzip)
index.html (97%, gzip)
websocket/index.html (42%, gzip)
cd /opt/source/libesphttpd_linux/libesphttpd_linux_example/httpd/html && objcopy -I binary -O elf64-x86-64 -B i386 --rename-section .data=.rodata /opt/source/libesphttpd_linux/libesphttpd_linux_example/build/httpd-prefix/src/httpd-build/webpages.espfs /opt/source/libesphttpd_linux/libesphttpd_linux_example/build/httpd-prefix/src/httpd-build/webpages.espfs.o.tmp
cd /opt/source/libesphttpd_linux/libesphttpd_linux_example/httpd/html && gcc -nostdlib -Wl,-r /opt/source/libesphttpd_linux/libesphttpd_linux_example/build/httpd-prefix/src/httpd-build/webpages.espfs.o.tmp -o /opt/source/libesphttpd_linux/libesphttpd_linux_example/build/httpd-prefix/src/httpd-build/webpages.espfs.o -Wl,-T /opt/source/libesphttpd_linux/libesphttpd_linux_example/httpd/linker.ld
/usr/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
CMakeFiles/libwebpages_target.dir/build.make:80: recipe for target 'libwebpages-espfs.a' failed
make[6]: *** [libwebpages-espfs.a] Error 1
[...]

It seems there is some "-pie stuff" involved in mkespfsimage building before COMMAND gcc -nostdlib -Wl,-r ... from libesphttpd_linux_example/httpd/CMakeLists.txt.

I cannot figure out how to handle this.
Can someone help me with this?

Thanks and best regards,

Bastian.

**Comment by phatpaul** [comment]
Unfortunately the Linux port hasn't been maintained and there has been a lot of changes that probably haven't been tested on Linux.
I don't have the free time at the moment, @jkent can you help?

**Comment by lumax** [comment]
Hello,
thank you for the answer.
I can imagine that time is short. I will continue without a Linux test environment for the time being. Libesphttpd is a cool thing,
thank you for your efforts.

Best wishes,

Bastian.
